### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by chris-y** [JoshuaSmeda/mimecast_log_collector#7]
The log collector seems to be utilising more CPU than it should today.
I think this may be because the ttp and audit logs are continually checking and then checking the hashes (I'm getting many hash already exists messages within milliseconds of each other)
Maybe this should be rate limited to only check every thirty seconds?

**Comment by JoshuaSmeda** [comment]
I have noted higher than usual CPU usage - it's due to the TTP and Audit events & and the hashing.

I'll add a custom rate limiter later today.

**Comment by JoshuaSmeda** [comment]
Let me know if that helps you out abit @chris-y.

Just set the interval timer in `configuration.py` under `logging_details` to a int (in seconds). Only applies to TTP and Audit events.

**Comment by chris-y** [comment]
Hmm, doesn't seem to have helped, still getting duplicate "hash already exists" within seconds of each other (9 seconds, delay is 25), and at least one thread constantly at 98-100% CPU (although it does seem to drop off for a bit now if I watch it, which is better, but still not right)
![image](https://user-images.githubusercontent.com/1818803/71074285-e5e57100-2179-11ea-972f-4cceb769eed9.png)

**Comment by JoshuaSmeda** [comment]
The hash just prints so we can ignore that for now. I just put that there so we know that the collector is actually doing work. If you want to hide it. Change line text:

```print("Hash %s already exists" % (hashed_event))```

to

``` pass ```

in audit_events & ttp_events python files.

Can you try raising your interval to 60 instead of 25 and see if it makes a overall difference? Also what is your IO usage like on the box you're collecting from - is it high?

You can use https://github.com/amanusk/s-tui to get an idea if changing the interval makes an improvement.

I still need to make more improvements in terms of performance. I'll get to it when I have some time to work on that stage. I'll also make some improvements that will make it easier to debug rogue threads (high usage).

**Comment by chris-y** [comment]
I've set it to 60, I'll monitor for a bit.
IO usage is low, CPU usually sits at less than 10%.

**Comment by chris-y** [comment]
It has definitely improved.  CPU still higher than I'd like, but now sitting at around 20-30% (peaking at ~50%)

**Comment by JoshuaSmeda** [comment]
Good to hear Chris,

You can increase the interval timer until you're happy with the usage. I'll
prioritize the performance issues.

**Comment by JoshuaSmeda** [comment]
I've refactored and attempted to improve the performance

I haven't tested this fully yet so cannot confirm but it should be a lot more efficient.

https://github.com/JoshuaSmeda/mimecast_log_collector/tree/improve_performance

**Comment by chris-y** [comment]
I've switched over to that version, looks good so far, will monitor.

**Comment by JoshuaSmeda** [comment]
Hey @chris-y,

Is it running better on your side now?

**Comment by chris-y** [comment]
Yes, has been running wonderfully!
